README spanish version
adafruit/iot-bill-of-rights pull request #2
Opened 2017-12-14 18:07 UTC by sabas1080

Hi

Im create the version in spanish, i hope you like it

:D

2017-12-19 00:56 UTC, ghost approved these changes

2017-12-19 15:27 UTC, fede2cr requested changes
On line 15, I would end it with "y otros deben indicar claramente cuando están encendidos y están escuchando, o cuando estén apagados y no lo están."

On line 17: "por favor realice un fork a este repositorio"

2017-12-19 17:59 UTC, ladyada commented
hiya if y'all all agree with this translation i'll merge it, thx :)

2018-01-25 19:38 UTC, tannewt commented
Looks like folks agree. Merging now! Please propose other PRs if you have additional changes.

2018-01-25 19:38 UTC, merged